server:
  port: 8765


spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#        - AddResponseHeader=Access-Control-Allow-Origin, *
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowed-origins: "*"
#            allowed-methods:
#              - GET
#              - POST
#              - PUT
      routes:
        - id: category
          uri: lb://CATEGORY
          predicates:
            - Path=/api/v1/categories/**

        - id: medicine
          uri: lb://MEDICINE
          predicates:
            - Path=/api/v1/medicines/**

        - id: pharmacy
          uri: lb://PHARMACY
          predicates:
            - Path=/api/v1/pharmacies/**

        - id: stock
          uri: lb://STOCK
          predicates:
            - Path=/api/v1/stocks/**

        - id: users
          uri: lb://USERS
          predicates:
            - Path=/api/v1/users/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: localhost:${server.port}