server:
  port: 8600

spring:
  application:
    name: users

  datasource:
    url: jdbc:mysql://localhost:3306/java_senepharma_users
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ***********
    password: ***********

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: localhost:${server.port}
