server:
  port: 8080

spring:
  application:
    name: pharmacy

  datasource:
    url: jdbc:mysql://localhost:3306/java_senepharma_pharmacies
    username: root
    password: dieme
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect